# French translations for INSECA package.
# Copyright (C) 2022 THE INSECA'S COPYRIGHT HOLDER
# This file is distributed under the same license as the INSECA package.
# Automatically generated, 2022.
# Vivien Malerba <vmalerba@gmail.com>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: INSECA 2\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-02-18 17:47+0100\n"
"PO-Revision-Date: 2022-01-30 14:30+0100\n"
"Last-Translator: Vivien Malerba <vmalerba@gmail.com>\n"
"Language-Team: français <vmalerba@gmail.com>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"X-Generator: Gtranslator 3.30.1\n"

#: ../lib/AppendedData.py:40 ../lib/AppendedData.py:42
#, python-format
msgid "Could not find reference '%s'"
msgstr "Impossible de trouver la référence '%s'"

#: ../lib/AppendedData.py:74
msgid "In creation mode, both specs and layout are expected"
msgstr ""

#: ../lib/AppendedData.py:81
#, python-brace-format
msgid "Device file mismatch: '{devfile}' specified and '{layout}' in layout"
msgstr ""

#: ../lib/AppendedData.py:105
#, python-format
msgid "Unknown partitioning type '%s'"
msgstr ""

#: ../lib/AppendedData.py:115
#, python-brace-format
msgid ""
"Not enough reserved space on device (got {offset} out of {reserved} reserved)"
msgstr ""

#: ../lib/AppendedData.py:121
msgid "Actual metadata has not yet been created or read from the device"
msgstr ""

#: ../lib/AppendedData.py:128
msgid "Not enough reserved space for metadata's length"
msgstr ""

#: ../lib/AppendedData.py:167
msgid "Absent or invalid device signature"
msgstr ""

#: ../lib/AppendedData.py:183
msgid "Can't create metadata in non creation mode"
msgstr ""

#: ../lib/AppendedData.py:262 ../lib/AppendedData.py:331
msgid "Actual metadata has been read from the device"
msgstr ""

#: ../lib/AppendedData.py:264
msgid "No metadata verifiers provided"
msgstr ""

#: ../lib/AppendedData.py:279
msgid ""
"No matching signature verifer: metadata's signature could not be verified"
msgstr ""

#: ../lib/AppendedData.py:288
msgid "H/W model mismatch: wrong device"
msgstr ""

#: ../lib/AppendedData.py:294
msgid "Serial numbers mismatch: wrong device"
msgstr ""

#: ../lib/AppendedData.py:298
msgid "Device size mismatch: wrong device"
msgstr ""

#: ../lib/AppendedData.py:304
#, python-brace-format
msgid "Partition label scheme has been altered from '{etype}' to '{gtype}'"
msgstr ""

#: ../lib/AppendedData.py:308
msgid "Partition table has been altered"
msgstr ""

#: ../lib/AppendedData.py:318
#, python-brace-format
msgid ""
"Filesystem for partition {number} has been modified from '{fs}' to '{fstype}'"
msgstr ""

#: ../lib/AppendedData.py:323
#, python-format
msgid "Partition %d has been altered"
msgstr ""

#: ../lib/AppendedData.py:327
#, python-format
msgid "Files in partition %d have changed"
msgstr ""

#: ../lib/AppendedData.py:346
msgid "Can't create security data in non creation mode"
msgstr ""

#: ../lib/Borg.py:98
#, fuzzy, python-format
msgid "Could not initialize repository: %s"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:120
#, fuzzy, python-format
msgid "Could not create archive: %s"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:139 ../lib/Borg.py:179 ../lib/Borg.py:203 ../lib/Borg.py:244
#: ../lib/Borg.py:281
msgid "Incomplete synchronisation, retry later"
msgstr ""

#: ../lib/Borg.py:141
#, python-format
msgid "Failed to get archives list: %s"
msgstr ""

#: ../lib/Borg.py:181
#, python-format
msgid "Could not list archives: %s"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:190
msgid "Archive to extract is not specified"
msgstr ""

#: ../lib/Borg.py:192
#, python-format
msgid "Destination path '%s' does not exist"
msgstr ""

#: ../lib/Borg.py:194
#, python-format
msgid "Destination path '%s' is not a directory"
msgstr ""

#: ../lib/Borg.py:205
#, python-format
msgid "Could not extract archive: %s"
msgstr ""

#: ../lib/Borg.py:246
#, python-brace-format
msgid "Could not mount archive '{archive_name}': {err}"
msgstr ""

#: ../lib/Borg.py:249
#, python-brace-format
msgid "Mounted archive '{archive_name}' on '{mp}'"
msgstr ""

#: ../lib/Borg.py:274
#, python-format
msgid "Could not umount archive '%s': timed out"
msgstr ""

#: ../lib/Borg.py:283
#, python-brace-format
msgid "Could not umount archive '{archive_name}': {err}"
msgstr ""

#: ../lib/Borg.py:291
#, python-brace-format
msgid "Unmounted archive '{archive_name}' (was mounted on '{mp}')"
msgstr ""

#: ../lib/Configurations.py:48 ../lib/Configurations.py:65
#, python-format
msgid "Missing attribute '%s'"
msgstr ""

#: ../lib/Configurations.py:52
#, python-format
msgid "Invalid attribute '%s': should not be null"
msgstr ""

#: ../lib/Configurations.py:54
#, python-format
msgid "Invalid attribute '%s': wrong data type"
msgstr ""

#: ../lib/Configurations.py:58
#, python-format
msgid "Expected a dictionary, got: %s"
msgstr ""

#: ../lib/Configurations.py:62
#, python-format
msgid "Invalid attribute '%s'"
msgstr ""

#: ../lib/Configurations.py:68
msgid "Invalid 'descr' attribute: wrong type"
msgstr ""

#: ../lib/Configurations.py:70
#, python-format
msgid "Invalid 'type' attribute '%s'"
msgstr ""

#: ../lib/Configurations.py:72
msgid "Invalid 'attest' attribute: wrong type"
msgstr ""

#: ../lib/Configurations.py:78
#, python-format
msgid "Wrong value '%s' for a string parameter"
msgstr ""

#: ../lib/Configurations.py:85
#, python-format
msgid "Missing file '%s' identified in parameter"
msgstr ""

#: ../lib/Configurations.py:88
#, python-format
msgid "Wrong value '%s' for parameter"
msgstr ""

#: ../lib/Configurations.py:93
#, python-format
msgid "Wrong value '%s' for a filesystem parameter"
msgstr ""

#: ../lib/Configurations.py:134 ../lib/Configurations.py:314
#: ../lib/Configurations.py:491 ../lib/Configurations.py:629
#: ../lib/Configurations.py:700
#, python-brace-format
msgid "Invalid file '{configfile}' format: {err}"
msgstr ""

#: ../lib/Configurations.py:194
#, python-format
msgid "Missing live Linux signing private key file '%s'"
msgstr ""

#: ../lib/Configurations.py:206
#, python-format
msgid "Missing live Linux signing public key file '%s'"
msgstr ""

#: ../lib/Configurations.py:428
#, python-brace-format
msgid "Invalid install configuration '{config_file}': {err}"
msgstr ""

#: ../lib/Configurations.py:453 ../lib/Configurations.py:591
#, python-format
msgid "Invalid parameter '%s': already part of core configuration"
msgstr ""

#: ../lib/Configurations.py:463 ../lib/Configurations.py:601
#, python-brace-format
msgid ""
"Invalid configuration entry '{entry}' in section '{section}': already part "
"of core configuration"
msgstr ""

#: ../lib/Configurations.py:568
#, python-brace-format
msgid "Invalid format configuration '{config_file}': {err}"
msgstr ""

#: ../lib/Configurations.py:745
#, python-brace-format
msgid "Could not get actual size of '{self.path}': {err}"
msgstr ""

#: ../lib/Configurations.py:770
msgid "Invalid configuration: not a dictionary"
msgstr ""

#: ../lib/Configurations.py:784
#, python-brace-format
msgid "Invalid repo configuration '{config_file}': {err}"
msgstr ""

#: ../lib/Configurations.py:789
#, python-brace-format
msgid ""
"Invalid repo configuration '{config_file}': path '{path}' does not exist"
msgstr ""

#: ../lib/Configurations.py:794
#, python-brace-format
msgid "Invalid repo configuration '{config_file}': invalid type '{self._type}'"
msgstr ""

#: ../lib/Configurations.py:916
#, python-format
msgid "Root directory '%s' is not empty"
msgstr ""

#: ../lib/Configurations.py:937
msgid "INSECA_ROOT environment variable is not defined"
msgstr ""

#: ../lib/Configurations.py:940
#, python-format
msgid ""
"Directory '%s' pointed by INSECA_ROOT environment variable does not exist"
msgstr ""

#: ../lib/Configurations.py:947
#, python-format
msgid "Top directory '%s' is missing"
msgstr ""

#: ../lib/Configurations.py:949
#, python-format
msgid "'%s' should be a directory"
msgstr ""

#: ../lib/Configurations.py:994
msgid "The archives_cache_dir property has not yet been defined"
msgstr ""

#: ../lib/Configurations.py:1036
#, python-format
msgid "Global configuration file '%s' is missing"
msgstr ""

#: ../lib/Configurations.py:1055
#, python-brace-format
msgid "'reader-conf' file '{fname}' not found for entry '{entry}'"
msgstr ""

#: ../lib/Configurations.py:1062
#, python-brace-format
msgid "'writer-conf' file '{fname}' not found for entry '{entry}'"
msgstr ""

#: ../lib/Configurations.py:1100
#, python-format
msgid "Unknown synchronization target '%s'"
msgstr ""

#: ../lib/Configurations.py:1145
#, python-brace-format
msgid "Build configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1165 ../lib/Configurations.py:1200
#, python-brace-format
msgid "Install configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1180
#, python-format
msgid "Missing format configuration file '%s'"
msgstr ""

#: ../lib/Configurations.py:1184
#, python-brace-format
msgid "Format configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1224
#, python-brace-format
msgid "Repository configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1240
#, python-brace-format
msgid ""
"Install configuration '' references inexistant build ID '{iconf.build_id}'"
msgstr ""

#: ../lib/Configurations.py:1244
#, python-brace-format
msgid ""
"Install configuration '{path}' references live Linux build configuration "
"which has no associated repository"
msgstr ""

#: ../lib/Configurations.py:1248
#, python-brace-format
msgid ""
"Install configuration '{path}' references inexistant build repository 'iconf."
"build_repo_id'"
msgstr ""

#: ../lib/Configurations.py:1252
#, python-brace-format
msgid ""
"Install configuration '{path}' references build repo ID '{iconf."
"build_repo_id}' which is not of type BUILD"
msgstr ""

#: ../lib/Configurations.py:1257
#, python-brace-format
msgid ""
"Install configuration '{path}' references inexistant repo ID '{iconf."
"repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1260
#, python-format
msgid ""
"Install configuration '%s' references repo ID which is not of type INSTALL"
msgstr ""

#: ../lib/Configurations.py:1269
#, python-brace-format
msgid ""
"Format configuration '{path}' references inexistant repo ID '{fconf.repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1272
#, python-format
msgid ""
"Format configuration '%s' references repo ID which is not of type FORMAT"
msgstr ""

#: ../lib/Configurations.py:1281
#, python-brace-format
msgid ""
"Build configuration '{path}' references inexistant repo ID '{bconf.repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1284
#, python-format
msgid "Build configuration '%s' references repo ID which is not of type BUILD"
msgstr ""

#: ../lib/Configurations.py:1292
#, python-brace-format
msgid ""
"Domain configuration '{path}' references inexistant repo ID '{dconf.repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1296
#, python-brace-format
msgid ""
"Domain configuration '{path}' references domain repo ID '{dconf.repo_id}' "
"which is not of type DOMAIN"
msgstr ""

#: ../lib/Configurations.py:1299
#, python-format
msgid ""
"Invalid 'install-ref' part in domain configuration: references unknown "
"install configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1324 ../lib/Configurations.py:1354
#: ../lib/Configurations.py:1384 ../lib/Configurations.py:1414
msgid "More than one matching configuration"
msgstr ""

#: ../lib/Configurations.py:1331
#, python-format
msgid "Unknown build configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1361
#, python-format
msgid "Unknown install configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1391
#, python-format
msgid "Unknown format configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1421
#, python-format
msgid "Unknown domain configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1439
#, python-format
msgid "Unknown repo configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1456
msgid "No build archive available"
msgstr ""

#: ../lib/Configurations.py:1459 ../lib/Configurations.py:1481
#, python-format
msgid "No archive '%s' in repository"
msgstr ""

#: ../lib/Configurations.py:1467
#, python-brace-format
msgid ""
"Build repo '{rconf.id}' seems corrupted: missing the 'live-linux.iso' file "
"in archive '{barname}'"
msgstr ""

#: ../lib/Configurations.py:1470
#, python-brace-format
msgid ""
"Build repo '{rconf.id}' seems corrupted: missing the 'live-linux.userdata-"
"specs' file in archive '{barname}'"
msgstr ""

#: ../lib/Configurations.py:1510
msgid ""
"Archives cache directory cannot be a subdirectory of the configuration's "
"global directory"
msgstr ""

#: ../lib/CryptoGen.py:38
#, python-format
msgid "Password is too short (%d characters)"
msgstr ""

#: ../lib/CryptoGen.py:42
#, python-format
msgid "Alphabet to generate password from is too small: %d long"
msgstr ""

#: ../lib/CryptoGen.py:51
#, python-format
msgid "Invalid character '%s'"
msgstr ""

#: ../lib/CryptoGen.py:54 ../lib/CryptoPass.py:63
msgid "Invalid password: not strong enough"
msgstr ""

#: ../lib/CryptoGen.py:165
msgid "Invalid data: can't convert from ascii"
msgstr ""

#: ../lib/CryptoPass.py:61
msgid "Invalid password: expected a string"
msgstr ""

#: ../lib/CryptoPass.py:77
#, python-format
msgid "Could not encrypt data with password: %s"
msgstr ""

#: ../lib/CryptoPass.py:91 ../lib/CryptoX509.py:131
#, python-format
msgid "Invalid format for data to decrypt '%s'"
msgstr ""

#: ../lib/CryptoPass.py:99
#, python-format
msgid "Could not decrypt data using password: %s"
msgstr ""

#: ../lib/CryptoPass.py:130
msgid "Could not verify the signature"
msgstr ""

#: ../lib/CryptoX509.py:37
#, python-format
msgid "Could not generate a new private RSA key: %s"
msgstr ""

#: ../lib/CryptoX509.py:41
#, python-format
msgid "Could not generate a new public RSA key: %s"
msgstr ""

#: ../lib/CryptoX509.py:49
#, python-format
msgid "Could not extract public key from certificate: %s"
msgstr ""

#: ../lib/CryptoX509.py:54
msgid "Could not determine public key type of certificate"
msgstr ""

#: ../lib/CryptoX509.py:67
#, python-brace-format
msgid "Could not sign file '{data_file}': {err}"
msgstr ""

#: ../lib/CryptoX509.py:79
#, python-brace-format
msgid "Signature verification failed for file '{data_file}': {err}"
msgstr ""

#: ../lib/CryptoX509.py:92
msgid "No public key provided, can't encrypt"
msgstr ""

#: ../lib/CryptoX509.py:107
#, python-format
msgid "Could not encrypt symetric key with certificate's public key: %s"
msgstr ""

#: ../lib/CryptoX509.py:114
#, python-format
msgid "Could not encrypt data with symetric key: %s"
msgstr ""

#: ../lib/CryptoX509.py:143
#, python-format
msgid "Could not decrypt intermediate symetric key: %s"
msgstr ""

#: ../lib/CryptoX509.py:151
#, python-format
msgid "Could not decrypt data using symetric key: %s"
msgstr ""

#: ../lib/CryptoX509.py:162
msgid "No private key provided, can't sign"
msgstr ""

#: ../lib/CryptoX509.py:174
#, fuzzy, python-format
msgid "Could not create signature: %s"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/CryptoX509.py:189
msgid "No public key provided, can't verify signature"
msgstr ""

#: ../lib/CryptoX509.py:198
msgid "Invalid signature format"
msgstr ""

#: ../lib/CryptoX509.py:212
#, python-format
msgid "Unable to verify signature: %s"
msgstr ""
